image: "alpine:latest"

before_script:
    - sed -i 's/dl-cdn.alpinelinux.org/mirrors.tuna.tsinghua.edu.cn/g' /etc/apk/repositories
    # - mkdir -p /etc/apk-cache
    # - ln -s /etc/apk/cache /etc/apk-cache
    # - apk cache sync -v


variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
    GIT_SUBMODULE_STRATEGY: recursive

build:
    stage: build
    before_script:
        - sed -i 's/dl-cdn.alpinelinux.org/mirrors.tuna.tsinghua.edu.cn/g' /etc/apk/repositories
        - apk add cmake gcc g++ libgcc build-base make --no-cache
    script:
        - ls -la
        - mkdir -p build
        - cd build
        - cmake -DSTATIC_LINK_ARTIFACTS=1 ..
        # do not use all cores on rpi; might heat it to crash.
        - make -j3
    cache:
        paths:
            - build/
    artifacts:
        paths:
            - build/compiler
        expire_in: 1 week
test:
    stage: test
    cache:
        paths:
            - .cache/pip
            - venv/
    dependencies:
        - build
    before_script:
        - sed -i 's/dl-cdn.alpinelinux.org/mirrors.tuna.tsinghua.edu.cn/g' /etc/apk/repositories
        - apk add python3 py3-pip gcc libgcc build-base --no-cache
        - python3 -V               # Print out python version for debugging
        - pip3 install -i https://pypi.tuna.tsinghua.edu.cn/simple --ignore-installed virtualenv
        - virtualenv venv
        - source venv/bin/activate
        - pip3 install -i https://pypi.tuna.tsinghua.edu.cn/simple --ignore-installed colorlog tqdm
    script:
        - python3 scripts/test.py build/compiler test_codes/sysyruntimelibrary/libsysy.a test_codes/basic_test -r
