image: "alpine:latest"

cache:
    paths:
        - /etc/apk-cache/

before_script:
    - sed -i 's/dl-cdn.alpinelinux.org/mirrors.tuna.tsinghua.edu.cn/g' /etc/apk/repositories
    # - mkdir -p /etc/apk-cache
    # - ln -s /etc/apk/cache /etc/apk-cache
    # - apk cache sync -v
    - apk add autoconf build-base binutils cmake file gcc g++ git libgcc libtool linux-headers make musl-dev --no-cache

build:
    script:
        - ls -la
        - mkdir -p build
        - cd build
        - cmake -DSTATIC_LINK_ARTIFACTS=1 ..
        # do not use all cores on rpi; might heat it to crash.
        - make -j3
    artifacts:
        paths:
            - build/compiler
        expire_in: 1 week
test:
    before_script:
        - apk add python3 python3-dev python3-pip  --no-cache
        - pip3 install colorlog
        - pip3 install tqdm
    script:
        - python3 scripts/test.py build/compiler test_codes/sysyruntimelibrary/libsysy.a test_codes/basic_test -r
